package io.github.vouched;

import java.util.List;

public class CrossCheckIdentityEmail{
  public CrossCheckErrorEmail [] errors;
  public CrossCheckWarningEmail [] warnings;
  public boolean isValid;
  public boolean isMatch;
  public String name;
  public CrossCheckAgeRangeEmail ageRange;
  public boolean isAutoGenerated;
  public boolean isDisposable;
  public int daysFirstSeen;
}

